@startuml

skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

title "Athena System"
skinparam componentStyle uml2

cloud {
    actor "User" as user
    component "Pegasus" as pegasus
    storage "File Server" as storage
    queue "queue" as queue
    component "Draco" as draco
    component "Cygnus" as cygnus
    component "Andromeda" as andromeda
    database "database" as database

    user .down.> pegasus
    pegasus .down.> storage : 1. store fotos
    pegasus .down.> queue : 2. produce fotos infos

    draco <.up. queue : 3. consume fotos infos
    draco .up.> storage : 4. consume fotos
    draco .up.> queue : 5. produce numbers

    queue .up.> cygnus : 6. consume numbers
    cygnus .down.> database : 7. store numbers
    cygnus .up.> pegasus : 8. send reports

    database .up.> andromeda : 9. poll monthly numbers
    andromeda .right.> pegasus : 10. notify for fotos

}

@enduml
