@startuml

skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

title "Athena System"
skinparam componentStyle uml2

cloud {
    actor "User" as user
    component "Pegasus" as pegasus
    queue "queue" as queue
    component "Draco" as draco
    component "Cygnus" as cygnus
    component "Andromeda" as andromeda
    database "database" as database
    component "Phoenix" as phoenix
    cloud "ia" as ia

    user .down.> pegasus

    pegasus .down.> draco : 1. post fotos

    draco .down.> database : 2. store fotos
    draco .down.> queue : 3. produce fotos infos

    cygnus <.up. queue : 4. consume fotos infos
    cygnus <.up. draco : 5. consume fotos
    cygnus <..> ia : 6. detect numbers
    cygnus .up.> queue : 7. produce numbers

    andromeda .down.> queue : 8. consume numbers
    andromeda .down.> draco : 9. post numbers
    andromeda .up.> pegasus : 10. send reports

    draco .up.> phoenix : 11. poll monthly numbers
    phoenix .right.> pegasus : 12. notify for fotos
}

@enduml
