@startuml

skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

title "Athena System"
skinparam componentStyle uml2

cloud {
    actor "User" as user
    component "Pegasus" as pegasus
    storage "File Server" as storage
    queue "queue" as queue
    component "Draco" as draco
    component "Cygnus" as cygnus
    component "Andromeda" as andromeda
    database "database" as database
    component "Phoenix" as phoenix

    user .down.> pegasus

    pegasus .down.> draco : 1. send fotos

    draco .down.> storage : 2. store fotos
    draco .down.> queue : 3. produce fotos infos

    cygnus <.up. queue : 4. consume fotos infos
    cygnus .up.> storage : 5. consume fotos
    cygnus .up.> queue : 6. produce numbers

    andromeda .down.> queue : 7. consume numbers
    andromeda .down.> database : 8. store numbers
    andromeda .up.> pegasus : 9. send reports

    database .up.> phoenix : 10. poll monthly numbers
    phoenix .right.> pegasus : 11. notify for fotos

}

@enduml
